language: node_js
node_js:
  - "10"
env:
  - CODECOV_TOKEN="f0dbb006-6aa1-425f-8604-77dec84da322" spec=true
install:
  - npm install
script:
  - npm test
  - codecov -f .nyc_output/*.json
before_script:
  - npm run build
services:
  - mongodb